### ISSUE TITLE
Problems with version 4.7.0

### ISSUE THREAD

**Issue by godotalgorithm** [jmarrec/setup-qtifw#187]
I've been using this Action in my GHA jobs with qtifw-version: '4.x', which just changed from version 4.6.1 to version 4.7.0 at some point in the last week. Version 4.7.0 is not correctly installing on either Mac, Linux, or Windows. The installations all look pretty messed up in the GHA logs, so I don't think any further details are relevant. I'm avoiding this problem for now with a narrower version specification, but I would certainly like to keep up with QTIFW upgrades through this Action if possible.

**Comment by jmarrec** [comment]
More likely what's about to happen is that Qt 4.6.1 will be removed from the https://download.qt.io/official_releases/qt-installer-framework/ endpoint and it'll stop working altogether.

**Comment by jmarrec** [comment]
But you do make a good point that node16 is deprecated, so:

* https://github.com/jmarrec/setup-qtifw/pull/188
